sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ankurpal80/fibonacci-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ankurpal80/fibonacci-react npm run test

after_success:
  - docker build -t ankurpal80/fiboncacci-client ./client
  - docker build -t ankurpal80/fiboncacci-nginx ./nginx
  - docker build -t ankurpal80/fiboncacci-server ./server
  - docker build -t ankurpal80/fiboncacci-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub.
  - docker push ankurpal80/fiboncacci-client
  - docker push ankurpal80/fiboncacci-nginx
  - docker push ankurpal80/fiboncacci-server
  - docker push ankurpal80/fiboncacci-worker
